### ISSUE TITLE
When clicking gear icon on any talent loadout the row dissapears

### ISSUE THREAD

**Issue by jacobrreed** [NumyAddon/TalentTreeTweaks#29] opened 2023-11-09 19:42 UTC
When click the gear icon on builds to change name or set use default action bars the entire row dissapears
![image](https://github.com/NumyAddon/TalentTreeTweaks/assets/25580051/77625044-9f86-430d-a80e-b198be89e42f)
![image](https://github.com/NumyAddon/TalentTreeTweaks/assets/25580051/6347f624-66c8-4437-bd50-1b9128803cf5)

```
3x ...hEmotes/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:1735: attempt to index local 'dropDownFrame' (a nil value)
[string "@TwitchEmotes/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua"]:1735: in function `ToggleDropDownMenu'
[string "@TwitchEmotes/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua"]:135: in function <...hEmotes/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:130>
[string "@TwitchEmotes/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua"]:438: in function <...hEmotes/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:437>

Locals:
self = <table> {
 UIDropDownMenu_SetButtonText = <function> defined @TwitchEmotes/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:2056
 containsMouse = <function> defined @TwitchEmotes/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:1892
 UIDropDownMenu_DisableButton = <function> defined @TwitchEmotes/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:2040
 Create_UIDropDownCustomMenuEntry = <function> defined @TwitchEmotes/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:2255
 UIDropDownMenu_Refresh = <function> defined @TwitchEmotes/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:1426
 UIDropDownMenu_Initialize = <function> defined @TwitchEmotes/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:750
 UIDropDownMenu_SetSelectedName = <function> defined @TwitchEmotes/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:1540
 UIDropDownMenu_SetDropDownEnabled = <function> defined @TwitchEmotes/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:2082
 UIDropDownMenu_SetInitializeFunction = <function> defined @TwitchEmotes/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:774
 UIDropDownMenu_GetSelectedID = <function> defined @TwitchEmotes/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:1566
 UIDropDownMenu_MatchTextWidth = <function> defined @TwitchEmotes/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:1925
 DropDownExpandArrowMixin = <table> {
 }
 UIDropDownMenuButton_ShouldShowIconTooltip = <function> defined @TwitchEmotes/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:118
 UIDropDownMenu_InitializeHelper = <function> defined @TwitchEmotes/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:92
 DropDownMenuButtonMixin = <table> {
 }
 UIDropDownMenuButton_GetName = <function> defined @TwitchEmotes/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:2027
 UIDropDownMenu_ClearAll = <function> defined @TwitchEmotes/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:1972
 UIDropDownMenu_GetCurrentDropDown = <function> defined @TwitchEmotes/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:2015
 UIDropDownMenu_JustifyText = <function> defined @TwitchEmotes/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:1991
 UIDropDownMenu_IsEnabled = <function> defined @TwitchEmotes/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:2131
 UIDropDownMenu_RefreshDropDownSize = <function> defined @TwitchEmotes/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:805
 UIDropDownMenu_EnableButton = <function> defined @TwitchEmotes/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:2044
 UIDropDownMenu_SetFrameStrata = <function> defined @TwitchEmotes/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:801
 UIDropDownMenu_AddButton = <function> defined @TwitchEmotes/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:970
 UIDropDownMenu_GetButtonWidth = <function> defined @TwitchEmotes/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:1381
 CloseDropDownMenus = <function> defined @TwitchEmotes/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:1853
 UIDropDownMenu_HandleGlobalMouseEvent = <function> defined @TwitchEmotes/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:1897
 ColorPicker_GetPreviousValues = <function> defined @TwitchEmotes/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:2158
 Create_UIDropDownMenu = <function> defined @TwitchEmotes/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:736
 UIDropDownMenu_SetButtonWidth = <function> defined @TwitchEmotes/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:1952
 UIDropDownCustomMenuEntryMixin = <table> {
 }
 UIDropDownMenuButton_OpenColorPicker = <function> defined @TwitchEmotes/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:2031
 UIDropDownMenu_AddSeparator = <function> defined @TwitchEmotes/Libs/LibUIDropDownMenu/LibUIDropDownMe
 ```

**Comment by Numynum** [comment] 2023-11-09 20:16
closing as a duplicate of #28 
thanks for the error message though, it helps ^^

**Closed by Numynum** 2023-11-09 20:16 UTC
